name 'odoo_install'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures odoo_install'
long_description 'Installs/Configures odoo_install'
version '0.1.0'
