name 'install_apache'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures install_apache'
long_description 'Installs/Configures install_apache'
version '0.1.0'
