---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.34.34"}] 

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
      customize:
        memory: 512

suites:
  - name: default
    run_list:
      - recipe[install_odoo::default]
    attributes:
