name 'install_odoo'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures install_odoo'
long_description 'Installs/Configures install_odoo'
version '0.1.0'
depends 'apt', '~> 3.0.0'
depends 'postgresql', '~> 4.0.4'
depends 'database', '~> 5.0.1'
