name 'install_postgres'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures install_postgres'
long_description 'Installs/Configures install_postgres'
version '0.1.0'
